language: python

# Default distro does not support python 3.7.
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
# Note: I want 3.7 because it adds "capture_output" to subprocess.run().
sudo: required
dist: xenial
python: '3.7'

cache: pip
install:
  - pip install -r requirements-dev.txt
script:
  - ./test.sh
